steps:
  - name: 'gcr.io/cloud-builders/gradle:8.1.1-jdk17-alpine'
    args: ['--version', '--gradle-version', 'bootJar']

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build',
            '-t',
            'gcr.io/$PROJECT_ID/pokemon-service:$COMMIT_SHA',
            '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
           'gcr.io/$PROJECT_ID/pokemon-service:$COMMIT_SHA']
