steps:
  - name: 'gcr.io/cloud-builders/gradle:latest'
    args: ['clean', 'build']

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build',
            '-t',
            'gcr.io/graphic-matrix-308512/pokemon-service:latest',
            '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
           'gcr.io/graphic-matrix-308512/pokemon-service:latest']
