version: '3.8'
services:
  pokemon-service:
    container_name: pokemon-service
#    image: ghcr.io/teunbuis-semester6-pogokwetter/pokemon-service:latest
    image: docker.io/teunbuis/pogokwetter:pokemon-service
    pull_policy: "always"
#    build:
#      context: ./
#      dockerfile: Dockerfile
    networks:
      - spring-net
    restart: "no"
    depends_on:
      - pokemonimg-mysql
      - rabbit-mq
      - pokemon-redis
    ports:
      - "8081:8081"


  pokemonimg-mysql:
    container_name: pokemonimg-mysql
    image: mysql:latest
    ports:
      - "3307:3307"
    networks:
      - spring-net
    environment:
      - MYSQL_ROOT_PASSWORD=Teun
      - MYSQL_DATABASE=pokemonimg
      - MYSQL_TCP_PORT=3307
    volumes:
      - pokemondata:/var/lib/mysql
      - pokemondata:/etc/mysql/conf.d

  user-mysql:
    container_name: user-mysql
    image: mysql:latest
    ports:
      - "3308:3308"
    networks:
      - spring-net
    environment:
      - MYSQL_ROOT_PASSWORD=Teun
      - MYSQL_DATABASE=user
      - MYSQL_TCP_PORT=3308
    volumes:
      - userdata:/var/lib/mysql
      - userdata:/etc/mysql/conf.d

  rabbit-mq:
    container_name: rabbit-mq
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - spring-net
    restart: "no"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  pokemon-redis:
    container_name: pokemon-redis
    image: redis:alpine
    command: redis-server --requirepass Teun
    networks:
      - spring-net
    ports:
      - "6379:6379"
    volumes:
      - pokemonredis:/data

  pokemon-gateway:
    container_name: pokemon-gateway
    image: ghcr.io/teunbuis-semester6-pogokwetter/pokemon-gateway:latest
    ports:
      - "8080:8080"
    networks:
      - spring-net

  redis-insight:
    container_name: redis-insight
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    networks:
      - spring-net

networks:
  spring-net:
    name: spring-net
    driver: bridge

volumes:
  pokemondata:
  pokemonredis:
  userdata: