version: '3.8'
services:
  pokemon-service:
    container_name: pokemon-service
    networks:
      - spring-net
    restart: "no"
    depends_on:
      - pokemon-mysql
    image: ghcr.io/teunbuis-semester6-pogokwetter/pokemon-service:latest
    ports:
      - "8080:8080"

  pokemon-mysql:
    container_name: pokemon-mysql
    image: mysql:latest
    ports:
      - "306:3306"
    networks:
      - spring-net
    environment:
      - MYSQL_ROOT_PASSWORD=Teun
      - MYSQL_DATABASE=pokemon
    volumes:
      - pokemondata:/var/lib/mysql
      - pokemondata:/etc/mysql/conf.d

  rabbit-MQ:
    container_name: rabbit-MQ
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - spring-net
    restart: "no"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

networks:
  spring-net:
    name: spring-net
    driver: bridge

volumes:
  pokemondata: