apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.network/spring-net: "true"
    io.kompose.service: rabbit-mq
  name: rabbit-mq
spec:
  containers:
    - env:
        - name: RABBITMQ_DEFAULT_PASS
          value: password
        - name: RABBITMQ_DEFAULT_USER
          value: user
      image: rabbitmq:3-management
      name: rabbit-mq
      ports:
        - containerPort: 15672
        - containerPort: 5672
      resources: {}
  restartPolicy: Never
status: {}
