name: build services and push img

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  REGISTRY: ghcr.io
    
jobs:
  build-pokemon-service:
    name: Build pokemon service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2    
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2   

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Login To Registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Pokemon-Service Image
        working-directory: ./
        run: docker build -t ${{env.REGISTRY}}/teunbuis-semester6-pogokwetter/pokemon-service:latest .

      - name: Push Pokemon-Service Image
        working-directory: ./microservices/vehicle-service
        run: docker push ${{env.REGISTRY}}/teunbuis-semester6-pogokwetter/pokemon-service:latest
